apiVersion: v1
kind: Service
metadata:
  name: heart-api-service
  namespace: heart-api
  labels:
    app: heart-api
spec:
  type: NodePort
  selector:
    app: heart-api
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 8000
      nodePort: 30080
      name: http
